# Configuration file for Kumo vs CAISO Benchmark
# Remove all hardcoded values and make them configurable

# Data Sources Configuration
data_sources:
  weather:
    file_path: "data/meteostat_hourly.parquet"
    timestamp_columns: ["ts", "time"]
    feature_keywords: ["temp", "humid", "wind", "pressure", "precip", "snow"]
  
  ev_stations:
    file_path: "data/afdc_ev_stations_sf.parquet"
    access_code_column: "access_code"
    connector_types_column: "ev_connector_types"
    network_column: "ev_network"
    location_columns: ["latitude", "longitude"]
  
  distributed_generation:
    file_path: "data/ca_dg_sf.parquet"
    capacity_column: "capacity_mw"
    technology_column: "technology"
    
  # pge_customers: REMOVED - No longer needed!
  # POS 3.8 from ca_iso.pkl provides actual SF Bay Area customer load patterns
  # pge_customers:
  #   file_path: "data/pge_sf_q2_2025.parquet"  # File not needed
  #   usage_column: "totalkwh"
  #   class_column: "customerclass"
  #   min_records_threshold: 500
    
  caiso_data:
    file_path: "data/caiso_forecast_comparison.parquet"

# Directory Configuration
directories:
  runs_dir: "runs"
  data_dir: "data"

# File Patterns
file_patterns:
  enhanced_dataset: "enhanced_caiso_dataset_"
  caiso_training_dataset: "caiso_training_dataset_"
  caiso_kumo_training: "caiso_kumo_training_"
  kumo_caiso_benchmark: "kumo_caiso_benchmark_"

# Weather Features Configuration
weather_features:
  lag_hours: 24
  rolling_window_hours: 24
  heat_index_humidity_factor: 0.5

# EV Infrastructure Configuration
ev_infrastructure:
  # Connector type mappings
  dc_fast_connectors: ["J1772COMBO", "CHADEMO"]
  level2_connectors: ["J1772"]
  tesla_connectors: ["TESLA"]
  
  # Load modeling parameters
  base_load_per_station_mw: 0.05  # MW per Level 2 station
  dc_fast_multiplier: 3.0         # DC fast charging power multiplier
  min_ports_per_station: 2        # Minimum ports per station
  
  # Infrastructure scoring weights
  scoring_weights:
    public_access: 0.3
    dc_fast_charging: 0.4
    network_diversity: 0.2
    port_density: 0.1
  
  # Hourly load profiles (0.0 to 1.0 multipliers)
  hourly_load_profiles:
    0: 0.3   # Midnight
    1: 0.2
    2: 0.1
    3: 0.1
    4: 0.1
    5: 0.15
    6: 0.2   # Early morning
    7: 0.15
    8: 0.1
    9: 0.3   # Work day starts
    10: 0.4
    11: 0.5
    12: 0.6  # Midday
    13: 0.7
    14: 0.8
    15: 0.9
    16: 1.0  # Evening peak
    17: 1.2
    18: 1.4
    19: 1.3
    20: 1.1
    21: 0.9
    22: 0.7  # Night
    23: 0.5
  
  # Peak charging hours
  peak_charging_hours: [16, 17, 18, 19]
  overnight_charging_hours: [22, 23, 0, 1, 2, 3, 4, 5]

# Distributed Generation Configuration
distributed_generation:
  # California scaling factors (when SF data unavailable)
  ca_scaling:
    sf_population_fraction: 0.022  # SF is 2.2% of CA population
    ca_solar_capacity_mw: 12500
    ca_storage_capacity_mw: 850
    ca_total_projects: 750000
  
  # Default values when no data available
  defaults:
    penetration_rate: 0.15
    avg_system_size_kw: 7.5
  
  # Solar generation profiles (0.0 to 1.0 multipliers by hour)
  solar_generation_profiles:
    0: 0.0   # Night
    1: 0.0
    2: 0.0
    3: 0.0
    4: 0.0
    5: 0.0
    6: 0.05  # Dawn
    7: 0.15
    8: 0.35
    9: 0.55  # Morning
    10: 0.75
    11: 0.90
    12: 1.00 # Peak solar
    13: 0.98
    14: 0.92
    15: 0.82 # Afternoon
    16: 0.68
    17: 0.50
    18: 0.28
    19: 0.08 # Evening
    20: 0.01
    21: 0.0
    22: 0.0
    23: 0.0
  
  # Seasonal adjustments (by month)
  seasonal_adjustments:
    1: 0.7   # Winter
    2: 0.8
    3: 0.9
    4: 1.0   # Spring
    5: 1.1
    6: 1.2   # Summer
    7: 1.2
    8: 1.1
    9: 1.0   # Fall
    10: 0.9
    11: 0.8
    12: 0.7  # Winter
  
  # Storage discharge profiles (evening peak)
  storage_discharge_profiles:
    16: 0.2
    17: 0.5
    18: 0.8
    19: 1.0
    20: 0.7
    21: 0.4
    22: 0.1

# Temporal Features Configuration
temporal_features:
  # Holiday months (simplified)
  holiday_months: [1, 7, 11, 12]
  
  # Season transition months
  season_transition_months: [3, 6, 9, 12]
  
  # Business hours
  business_hours:
    start: 6
    end: 22
  
  # Peak pricing periods (TOU)
  peak_price_hours: [16, 17, 18, 19, 20, 21]
  weekdays_only: true

# Kumo Configuration
kumo:
  # API configuration (use environment variable for security)
  api_token_env_var: "KUMO_API_TOKEN"
  
  # Model training parameters
  training:
    sample_sizes: [100, 300, 1000]
    table_name_prefix: "temporal_"
    primary_key: "consumption_id"
  
  # Forecast horizons (days ahead)
  forecast_horizons:
    "7DA": 7   # 7-day ahead
    "2DA": 2   # 2-day ahead
    "DAM": 1   # Day-ahead market

# CAISO Benchmark Metrics (official performance targets)
caiso_benchmarks:
  "7DA":
    mae_mw: 676.8
    rmse_mw: 927.2
    mape_percent: 4.9
  "2DA":
    mae_mw: 542.4
    rmse_mw: 726.3
    mape_percent: 4.0
  "DAM":
    mae_mw: 498.6
    rmse_mw: 675.8
    mape_percent: 3.7

# Feature Selection Configuration
feature_selection:
  # Real features to keep (remove synthetic/constant features)
  real_features:
    caiso_core:
      - "actual_mw"
      - "forecast_7da_mw"
      - "forecast_2da_mw"
      - "forecast_dam_mw"
    
    temporal:
      - "hour"
      - "day_of_week"
      - "month"
      - "quarter"
      - "year"
      - "is_weekend"
      - "day_of_year"
      - "day_of_year_sin"
      - "day_of_year_cos"
      - "hour_sin"
      - "hour_cos"
      - "quarter_start"
      - "is_business_hours"
    
    weather:
      - "weather_temp"
      - "weather_wind_speed"
      - "weather_precip"
      - "weather_temp_lag_24h"
      - "weather_temp_rolling_mean_24h"
      - "weather_temp_volatility"
    
    load_patterns:
      - "load_lag_1h"
      - "load_lag_2h"
      - "load_lag_24h"
      - "load_lag_168h"
      - "load_rolling_mean_24h"
      - "load_rolling_std_24h"
      - "load_rolling_mean_168h"
      - "load_rolling_std_168h"
      - "daily_peak_mw"
      - "daily_min_mw"
      - "daily_avg_mw"
  
  # Columns to exclude
  exclude_columns:
    - "timestamp"
    - "OPR_DT"
  
  # NaN handling strategies by column type
  nan_handling:
    weather_columns:
      method: "forward_fill"  # Forward fill then backward fill
      fallback: 0
    lag_rolling_columns:
      method: "forward_fill"
      fallback: 0
    other_numeric:
      method: "median"

# Data Quality Configuration
data_quality:
  # Minimum dataset sizes
  min_dataset_sizes:
    pge_customers: 500
    ev_stations: 10
    weather_records: 100
  
  # Value limits
  value_limits:
    infinity_replacement:
      positive: 1e6
      negative: -1e6
  
  # Geographic bounds (for coverage calculation)
  geographic_bounds:
    default_coverage: 0.1

# Logging Configuration
logging:
  level: "INFO"
  show_progress: true
  show_feature_summaries: true
  show_data_quality_warnings: true
